name: update-features
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Run? (Optional)"
        required: false
        type: boolean
  push:
    branches:
      - main
      - feature-flow
    paths:
      - app/data/prep_agnews.py
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.13"
      - name: Load cached virtual environment
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: workflow/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/update-features.yaml') }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install libraries
        run: |
          poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Fetch data from DVC.
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo 'Downloading raw data'
          poetry run dvc pull data/input/raw/agnews.zip
          ls -lh data/input/raw
      - name: Update features
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          poetry run python -m app.data.prep_agnews
          poetry run dvc add data/input/processed/*.npz
      - name: Update DVC files in Git and DVC
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Modified processed data." -m "Initiated by commit ${{ github.sha }}"
          git push origin main
          poetry run dvc push
